### ISSUE TITLE
Help with eXtplorer

### ISSUE THREAD

**Issue by frankolious** [magdesign/PocketVJ-CP-v3#68]
I have followed the gist. updated to CP 2.4.1. Did the update all from /media/internal
and it is still CP2.4.1
Then I try to open eXtplorer and type in admin-admin for login and I get a white screen.

The error log 
 /var/log/lighttpd/error.log

shows

2018-12-12 20:13:24: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/eXtplorer/include/init.php:259
2018-12-12 20:13:24: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2018-12-12 20:13:24: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/eXtplorer/admin.extplorer.php(52): require_once()
2018-12-12 20:13:24: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /var/www/eXtplorer/index.php(46): include('/var/www/eXtplo...')
2018-12-12 20:13:24: (mod_fastcgi.c.2543) FastCGI-stderr: #2 {main}
2018-12-12 20:13:24: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/eXtplorer/include/init.php on line 259

**Comment by magdesign** [comment]
Which gist are you talking about?
Remove the login credentials, set the media folder in eXtplorer, make sure the userrights are set right.

Did you make: sudo lighty-enable-mod fastcgi-php
did you set the rights for www-data

**Comment by magdesign** [comment]
Did you find a solution for this or is this still an issue?

**Comment by kermit60fr** [comment]
hello 
installer php-xml
